#version: '3.8'
#
#services:
#  mysql:
#    image: mysql:8.0.46
#    container_name: spring-mysql-container
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: jdc_sms_db
#    volumes:
#      - mysql-data:/var/lib/mysql
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#      start_period: 15s
#
#volumes:
#  mysql-data: