spring.application.name=backend
spring.datasource.url=jdbc:mysql://mysql-db:3305/jdc_sms_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

